api_types = ["imageclassification","imagesegmentation","objectdetection"]
api_environments = ["development","staging","preproduction","production"]
api_methods = ["GET","POST","PUT","DELETE"]
api_input_data_types = ["url","file","base64"]
api_request_body_type = ["json","formData","binary","none"]
api_response_body_type = ["json","rawText"]